services:
  frontend:
    build: .
    ports: 
      - "80:80"
    depends_on:
      db:
        condition: service_started
        restart: true
    develop:
      watch:
        - action: sync
          path: .
          target: /WSApp

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: www-data
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysql
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./db:/var/lib/mysql
