services:
  frontend:
    build: .
    ports: 
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - action: sync
          path: .
          target: /WSApp

  backend:
    image: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p', 'password' ] 
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./db:/var/lib/mysql
