services:
  frontend:
    build: .
    ports: 
      - "80:80"
    depends_on:
      backend:
        condition: service_started
        restart: true
    volumes:
      - ./db:/WSApp/db
    develop:
      watch:
        - action: sync
          path: .
          target: /WSApp

  backend:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./db:/var/lib/mysql
