services:
  frontend:
    build: .
    ports: 
      - "80:80"
    volumes:
      - ./db:/WSApp/db
    develop:
      watch:
        - action: sync
          path: .
          target: /WSApp

  backend:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./db:/var/lib/mysql
