# Generated by Django 3.2.19 on 2025-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(verbose_name='temperature measurement')),
                ('humidity', models.FloatField(verbose_name='humidity measurement')),
                ('wind_speed', models.FloatField(verbose_name='wind speed')),
                ('wind_dir', models.CharField(max_length=2, verbose_name='wind direction')),
                ('pressure', models.FloatField(verbose_name='air pressure')),
                ('smoke', models.IntegerField(verbose_name='smoke level')),
                ('ambient', models.FloatField(verbose_name='ambient light level')),
                ('meas_time', models.DateTimeField(verbose_name='measurement time')),
            ],
        ),
    ]
